project_id = "yoegksjmdtubnkgdtttj"

[functions.send-admin-notification]
verify_jwt = false

[functions.parse-cv]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[functions.rescore-cvs]
verify_jwt = true

[functions.bypass-otp-login]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-daily-summary]
verify_jwt = false

[functions.match-cv-to-job]
verify_jwt = true

[functions.process-job-email]
verify_jwt = true

[functions.receive-email-webhook]
verify_jwt = false
